feature/Add speech to text typo
JohnSnowLabs/nlptest pull request #475
Opened 2023-05-30 11:25 UTC by Prikshit7766

## Checklist:

- [ ] I've added Google style docstrings to my code.
- [ ] I've used `pydantic` for typing when/where necessary.
- [ ] I have linted my code
- [ ] I have added tests to cover my changes.

2023-05-30 11:28 UTC, Prikshit7766 commented
time complexity issue
Now it is taking 
10- 12 minutes to generate the records for classification task  [Probelm]
1-2 minutes to generate the records for ner ,qa , summarization

2023-05-31 05:21 UTC, chakravarthik27 commented
Hey @Prikshit7766,
can you please resolve the conflicts by merging release/1.4.0

2023-05-31 05:24 UTC, chakravarthik27 commented on nlptest/utils/SoundsLikeFunctions.py
> +class Word_Functions():
remove brackets after the class name.

**Word_Functions()**: -> **Word_Functions**:

do the same thing for classes except those are inherited from other types.

2023-05-31 07:49 UTC, chakravarthik27 approved these changes

2023-05-31 11:44 UTC, chakravarthik27 commented on nlptest/transform/robustness.py
> +        for sample in sample_list:
it should be mandatory below line:
 for idx, sample in enumerate(sample_list):

2023-05-31 11:46 UTC, chakravarthik27 requested changes

2023-05-31 11:46 UTC, chakravarthik27 commented on nlptest/transform/robustness.py
> +        for sample in sample_list:
and write a code accordingly to uppercase or other test classes
bcoz, it handles both samples and strings from a list.

2023-05-31 12:26 UTC, Prikshit7766 commented
number to word and ocr typo working fine

2023-06-01 09:09 UTC, merged